### ISSUE TITLE
PDF Manual not available online

### ISSUE THREAD

**Issue by ruthhoffmann** [gap-packages/primgrp#29]
Note that in your README you point to `doc/manual.pdf` which is not pushed to this repository, nor is the pdf of the manual available at [http://gap-packages.github.io/primgrp/doc/manual.pdf](http://gap-packages.github.io/primgrp/doc/manual.pdf), but the html version of the manual does exist [http://gap-packages.github.io/primgrp/doc/chap0.html](http://gap-packages.github.io/primgrp/doc/chap0.html).

**Comment by alex-konovalov** [comment]
Thanks @ruthhoffmann but I don't think there is anything to do here. pdf (and html) are derived files and so should not be in the repository. The README refers to the package distribution, which included built manuals, so it's valid. The website of the package does not provide pdf versions, because we do not want to store binary files there. 

So, if you want a pdf version, the way to go is either to get it from the package distribution, or from the GAP distribution, or to go to the GAP website and find it under https://www.gap-system.org/Doc/manuals.html
